// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using html_24_03.Models;

#nullable disable

namespace html_24_03.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20220324183406_migracaoinicial")]
    partial class migracaoinicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("html_24_03.Models.Noticia", b =>
                {
                    b.Property<int>("noticiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("noticiaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("noticiaId"), 1L, 1);

                    b.Property<int>("noticiaDescr")
                        .HasColumnType("int")
                        .HasColumnName("noticiaId");

                    b.Property<int>("noticiaTexto")
                        .HasColumnType("int")
                        .HasColumnName("noticiaTexto");

                    b.HasKey("noticiaId");

                    b.ToTable("Noticia");
                });
#pragma warning restore 612, 618
        }
    }
}
